Revert "Client for distro check"
This reverts commit 4398c4c0f794fc29b70818fcd6b62caf21d8f59e.

Levi was correct. This can and will throw an error:

======================================================================
ERROR: setUpClass (cloudroast.compute.instance_actions.api.test_rebuild_server.ServerFromImageRebuildTests)
----------------------------------------------------------------------

.../cloudcafe/compute/common/clients/remote_instance/linux/linux_client.py", line 581, in get_distribution_and_version
    distro = result.stdout.split(':')[1]
IndexError: list index out of range

Change-Id: I672821182c0fb2deb16fbd74bc79ab26c440d411